### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class on FreeBSD

### ISSUE THREAD

**Issue by bryanhonof** [Valandur/admin-panel#5]
`[00:12:47 ERROR] [Sponge]: The Scheduler tried to run the task Web-API - Server stats owned by Plugin{id=webapi, name=Web-API, version=4.10.8-S7.1, description=Access Minecraft through a RESTful web server and an admin panel, url=https://github.com/Valandur/Web-API, authors=[Valandur], source=mods/webapi-4.10.8-S7.1.jar}, but an error occured.
java.lang.NoClassDefFoundError: Could not initialize class valandur.webapi.shadow.oshi.hardware.platform.unix.freebsd.FreeBsdGlobalMemory
        at valandur.webapi.shadow.oshi.hardware.platform.unix.freebsd.FreeBsdHardwareAbstractionLayer.getMemory(FreeBsdHardwareAbstractionLayer.java:53) ~[FreeBsdHardwareAbstractionLayer.class:?]
        at valandur.webapi.server.ServerService.recordStats(ServerService.java:75) ~[ServerService.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-7.1.0-BETA-18]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-7.1.0-BETA-18]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]`

**Comment by Valandur** [comment]
Hi, thanks again for the bug report.

I've had some time to look into this, and I'm not 100% sure what the cause is. I'm going to be setting up a unix/freebsd environment to try and reproduce this issue.  

Sorry for the delay
